name: reverb

networks:
    reverb:

services:
    nginx:
        container_name: reverb-nginx
        image: nginx:latest
        working_dir: /var/www/html
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        networks:
            reverb:
        ports:
            -   80:80
            -   443:443
        depends_on:
            -   php

    php:
        container_name: reverb-php
        build:
            context: .
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            reverb:
